/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlsinhvien;

import javax.swing.JOptionPane;

/**
 *
 * @author AN515-45
 */
public class SinhVienForm extends javax.swing.JFrame {

    /**
     * Creates new form SinhVienForm
     */
    SinhVienList sinhvienlist = new SinhVienList();
    int stt = - 1;
    private boolean allowFocusLost = true;

    public SinhVienForm() {
        initComponents();
        this.setLocationRelativeTo(null); // đưa form ra giữa màn hình
        khoiTaoDuLieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtmasv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttensv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txthocbong = new javax.swing.JTextField();
        btndau = new javax.swing.JButton();
        btntruoc = new javax.swing.JButton();
        btnsau = new javax.swing.JButton();
        btncuoi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        btnhuy = new javax.swing.JButton();
        btnghi = new javax.swing.JButton();
        btnkhong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Sinh Viên");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Mã SV");

        txtmasv.setEditable(false);
        txtmasv.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtmasv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmasvKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Tên SV");

        txttensv.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txttensv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttensvKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Học bổng");

        txthocbong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txthocbong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthocbongKeyTyped(evt);
            }
        });

        btndau.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btndau.setText("Đầu");
        btndau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndauActionPerformed(evt);
            }
        });

        btntruoc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btntruoc.setText("Trước");
        btntruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntruocActionPerformed(evt);
            }
        });

        btnsau.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnsau.setText("Sau");
        btnsau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsauActionPerformed(evt);
            }
        });

        btncuoi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btncuoi.setText("Cuối");
        btncuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuoiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("QUẢN LÝ SINH VIÊN");

        btnthem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnhuy.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnhuy.setText("Hủy");
        btnhuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuyActionPerformed(evt);
            }
        });

        btnghi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnghi.setText("Ghi");
        btnghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnghiActionPerformed(evt);
            }
        });

        btnkhong.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnkhong.setText("Không");
        btnkhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txttensv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(txtmasv, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txthocbong, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btndau, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btntruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnsau, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnhuy, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnghi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnkhong, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btncuoi, btndau, btnsau, btntruoc});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnghi, btnhuy, btnkhong, btnthem});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttensv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txthocbong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndau)
                    .addComponent(btntruoc)
                    .addComponent(btnsau)
                    .addComponent(btncuoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnhuy)
                    .addComponent(btnghi)
                    .addComponent(btnkhong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndauActionPerformed
        stt = 0;
        ganSinhVien(stt);
    }//GEN-LAST:event_btndauActionPerformed

    private void btntruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntruocActionPerformed
        if (stt == 0) {
            JOptionPane.showMessageDialog(this, "Không di chuyển về trước được", "Thông Báo !!!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        stt--;
        ganSinhVien(stt);
    }//GEN-LAST:event_btntruocActionPerformed

    private void btnsauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsauActionPerformed
        if (stt == sinhvienlist.tongSoSV() - 1) {
            JOptionPane.showMessageDialog(this, "Không di chuyển về sau được", "Thông Báo !!!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        stt++;
        ganSinhVien(stt);
    }//GEN-LAST:event_btnsauActionPerformed

    private void btncuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuoiActionPerformed
        stt = sinhvienlist.tongSoSV() - 1;
        ganSinhVien(stt);
    }//GEN-LAST:event_btncuoiActionPerformed

    private void btnkhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhongActionPerformed
        ganSinhVien(stt);
        // thiet lap che do không cho phép chỉnh sủa txtmasv
        txtmasv.setEditable(false);
        allowFocusLost = false; // Ngăn chặn việc bỏ focus
    }//GEN-LAST:event_btnkhongActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        txtmasv.setEditable(true); // cho phép chỉnh sửa
        txtmasv.setText("");
        txttensv.setText("");
        txthocbong.setText("");
        txtmasv.requestFocus(); // chuyển focus cho txtmasv
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnhuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuyActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa sinh viên không ?", "Cảnh Báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (choice == JOptionPane.YES_OPTION) {
            // Xác dịnh đối tượng sinh viên cần hủy
            SinhVien sv_huy = new SinhVien(txtmasv.getText());
            int chiMucSV = sinhvienlist.getDanhsach().indexOf(sv_huy);
            SinhVien sv = sinhvienlist.getDanhsach().get(chiMucSV);
            if (sinhvienlist.delSV(sv)) {
                JOptionPane.showMessageDialog(this, "Xóa sinh viên thành công!", "Thông Báo !!!", JOptionPane.INFORMATION_MESSAGE);
                ganSinhVien(0);
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi khi xóa sinh viên", "Thông Báo !!!", JOptionPane.INFORMATION_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnhuyActionPerformed

    private void btnghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnghiActionPerformed
        // Check lỗi 
        String loi = "";
        // txtmasv không dc rỗng 
        if(txtmasv.getText().length() == 0){
            loi += "Mã SV không được rỗng !!! \n";
        }
        // txttensv không dc rỗng
        if(txttensv.getText().length() == 0){
            loi += "Tên SV không được rỗng !!!";
        }
        if(loi.length()>0){
            JOptionPane.showMessageDialog(this, loi, "Thông Báo !!!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // txthocbong có quyền rỗng nhưng không dc nhập kí tự đặc biệc và chữ
        // Ghi sau khi thêm mới (txtmasv cho phép chỉnh sửa)
        SinhVien sv = new SinhVien(txtmasv.getText(), txttensv.getText(), Integer.parseInt(txthocbong.getText()));
        if (txtmasv.isEditable()) {
            // Ghi sau khi thêm mới 
            if (sinhvienlist.addSV(sv)) {
                JOptionPane.showMessageDialog(this, "Thêm sinh viên thành công", "Thông Báo !!!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Thêm sinh viên thất bại", "Thông Báo !!!", JOptionPane.INFORMATION_MESSAGE);
                txtmasv.requestFocus();
            }
            txtmasv.setEditable(false);
        } else {
            // Ghi sau khi sửa
            if (sinhvienlist.updateSV(sv)) {
                JOptionPane.showMessageDialog(this, "Sửa sinh viên thành công", "Thông Báo !!!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Sửa sinh viên thất bại", "Thông Báo !!!", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnghiActionPerformed

    private void txthocbongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthocbongKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || Character.isWhitespace(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txthocbongKeyTyped

    private void txttensvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttensvKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txttensvKeyTyped

    private void txtmasvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmasvKeyTyped
        char c = evt.getKeyChar();
        if (Character.isWhitespace(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtmasvKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SinhVienForm form = new SinhVienForm();
                form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncuoi;
    private javax.swing.JButton btndau;
    private javax.swing.JButton btnghi;
    private javax.swing.JButton btnhuy;
    private javax.swing.JButton btnkhong;
    private javax.swing.JButton btnsau;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntruoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txthocbong;
    private javax.swing.JTextField txtmasv;
    private javax.swing.JTextField txttensv;
    // End of variables declaration//GEN-END:variables

    private void khoiTaoDuLieu() {
        // Doc du lieu tu tap tin vao ArrayList<SinhVien>
        sinhvienlist.docDSSV();
        // Lay sinh vien thu stt voi stt = 0
        btndauActionPerformed(null); // Goi phuong thuc click cua nut btndau
    }

    private void ganSinhVien(int stt) {
        SinhVien sv = sinhvienlist.getDanhsach().get(stt);
        this.txtmasv.setText(sv.getMaSV());
        this.txttensv.setText(sv.getHoTenSV());
        this.txthocbong.setText(sv.getHocBong() + "");
    }

    public boolean chiChuaChu(String chuoi) {
        for (char c : chuoi.toCharArray()) {
            if (!Character.isLetter(c)) {
                return false;
            }
        }
        return true;

    }

    public boolean chiChuaSo(String chuoi) {
        try {
            Double.parseDouble(chuoi);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

}
